config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :beers, only: [:show] do
    get 'search', on: :collection
  end

  resources :school_beers, only: [:show] do
    get 'search', on: :collection
  end

  resources :bars, only:[:index, :show] do
    resources :checkins, only: [:create, :edit, :update]
  end

  resources :profiles, only:[:show, :update, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  has_many :bar_beers, dependent: :destroy
  has_many :beers, through: :bar_beers
  has_many :checkins, dependent: :destroy
end

app/models/bar_beer.rb
class BarBeer < ApplicationRecord
  belongs_to :bar
  belongs_to :beer
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :beer_style
  has_many :bar_beers, dependent: :destroy
  has_many :bars, through: :bar_beers
  has_many :checkins, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/beer_style.rb
class BeerStyle < ApplicationRecord
  belongs_to :school_beer
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :bar
  belongs_to :beer
  belongs_to :user

  def full_description
    "#{name_email} degustou a #{beers} no #{bars} em #{date_formatter}"
  end

  private

  def bars
    bar.name
  end

  def beers
    beer.name
  end

  def name_email
    user.profile.name.nil? ? user.email : user.profile.name
  end

  def date_formatter
    created_at.strftime('%d/%m/%Y às %H:%M')
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/school_beer.rb
class SchoolBeer < ApplicationRecord
  has_many :beers, dependent: :destroy
  has_many :beer_styles, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy

  has_many :checkins, dependent: :destroy

  after_create :create_profile

  private

  def create_profile
    Profile.create(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def show
    @bar = Bar.find(params[:id])
    @checkins = Checkin.where(bar: @bar).order('created_at DESC').first(10)
  end

  def index
    @bars = Bar.all
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def search
    @search = params[:q]
    @beers = Beer.where('name LIKE ?', "%#{@search}%")
  end

  def show
    @beer = Beer.friendly.find(params[:id])
    @checkins = Checkin.where(beer_id: @beer.id).order(created_at: :desc)
  end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :authenticate_user!
  def create
    checkin = Checkin.new(
      bar_id: params[:bar_id], beer_id: params[:beer_id], user: current_user
    )

    if checkin.save
      redirect_to edit_bar_checkin_path(
        bar_id: params[:bar_id], id: checkin.id
      )
    else
      flash[:error] = 'Houve algum problema'
    end
  end

  def edit
    @checkin = Checkin.find(params[:id])
    @full_description = @checkin.full_description
  end

  def update
    @checkin = Checkin.find(params[:id])
    @checkin.update(description: params[:description])

    redirect_to bar_path(@checkin.bar_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit]

  def show
    @profile = Profile.find_by(user_id: params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    return unless @profile.update(profile_params)
    flash[:notice] = 'Perfil atualizado com sucesso'

    redirect_to profile_path(@profile)
  end

  private

  def profile_params
    params.require(:profile).permit(:birth_date, :name)
  end
end

app/controllers/school_beers_controller.rb
class SchoolBeersController < ApplicationController
  def search
    @school_beer = SchoolBeer.find(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bars/index.html.erb
<% if @bars.empty? %>
  <div class="alert alert-danger" role="alert">Não existem bares cadastrados até o momento</div>
<% else %>
  <div class="row">
    <% @bars.each do |bar| %>
      <div class="col-md-4" style="margin-bottom: 2em">
        <%= render partial: "shared/bar", locals: {bar: bar} %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/bars/show.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<div class="row">
  <div class="col-md-4">
    <%= render partial: "shared/bar", locals: {bar: @bar} %>
  </div>

  <div class="col-md-4">
    <div class="card card--dark box-shadow">
      <div class="card-body">
        <h3>Cervejas Disponíveis</h3>
      </div>
      <div class="card-body data-list-container">
        <% if @bar.beers.empty? %>
          <div class="alert alert-danger" role="alert">Este bar não tem cerveja disponível no momento</div>
        <% else %>
          <ul class="list-group list-group-flush">
            <% @bar.beers.each do |beer| %>
              <li class="list-group-item text-light bg-dark">
                <%= link_to beer.name, beer_path(beer) %>
                  <%= link_to fa_icon('check-square'), bar_checkins_path(@bar, beer_id: beer.id), method: :post, class: 'check_link' if current_user %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card card--dark box-shadow">
      <div class="card-body">
        <h5 class="card-title">Últimos Checkins</h5>
      </div>
      <div class="card-body data-list-container">
        <% if @checkins.empty? %>
          <div class="alert alert-danger" role="alert">Este bar ainda não recebeu nenhum checkin =(</div>
        <% else %>
          <ul class="list-group list-group-flush">
            <% @checkins.each do |checkin| %>
              <li class="list-group-item checkin check_<%= checkin.created_at.to_i%> text-light bg-dark">
                <%= checkin.beer.name %> <small><i>há <%= time_ago_in_words(checkin.created_at) %></i></small>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/beers/search.html.erb
<% if @beers.empty? %>
  <div class='alert alert-warning' role='alert'>Cerveja não encontrada</div>
<% else %>
  <div class="row">
    <% @beers.each do |beer| %>
      <div class="col-md-4" style="margin-top: 2em">
        <div class="card card--dark box-shadow">
          <div class="card-header">
            <%= link_to beer.name, beer_path(beer)%>
          </div>
          <div class="card-body data-list-container">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-light bg-dark">Estilo: <%= beer.beer_style.name %></li>
              <li class="list-group-item text-light bg-dark">ABV: <%= beer.abv %>%</li>
              <li class="list-group-item text-light bg-dark">IBU: <%= beer.ibu %></li>
              <li class="list-group-item text-light bg-dark"><%= beer.beer_style.school_beer.name %></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/beers/show.html.erb
<div class="md-3 position-fixed">
  <div class="card card--dark md-5 box-shadow">
    <div class="card-img-top" style="width: 91px; important! height: 250px;">
      <%= image_tag '/images/beers/kbs.png', alt: 'Cervejaaaaaaaa =p' %>
    </div>
    <div class="card-body">
      <h3 class="card-title"><%= @beer.name %></h3>
    </div>
    <div class="card-body">
      <div class="list-group list-group-flush">
        <ul class="list-group list-group-flush">
          <li class="list-group-item text-light bg-dark"><h4>Estilo: <%= @beer.beer_style.school_beer.name %></h4></p>
          <li class="list-group-item text-light bg-dark"><h4>Estilo: <%= @beer.beer_style.name %></h4></p>
          <li class="list-group-item text-light bg-dark">Cervejaria: <%= @beer.brewery %></li>
          <li class="list-group-item text-light bg-dark">ABV: <%= @beer.abv %>%</li>
          <li class="list-group-item text-light bg-dark">IBU: <%= @beer.ibu %></li>
          <li class="list-group-item text-light bg-dark">Nacionalidade: <%= @beer.nationality %></li>
          <li class="list-group-item text-light bg-dark">Descrição: <%= @beer.description %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% if @beer.bars.empty? %>
  <div class="alert alert-danger" role="alert">No momento nenhum bar está oferecendo esta cerveja</div>
<% else %>
  <div style="margin-left: 450px">
    <% @beer.bars.each do |bar| %>
      <%= render partial: "shared/bar", locals: {bar: bar} %>
    <% end %>
  </div>
<% end %>


<div class="card card--dark md-2" style="float: right; margin-top: 15em; margin-left: 50px">
  <div class="card-body">
    <h5 class="card-title">Últimos Checkins</h5>
  </div>
  <div class="card-body data-list-container">
    <% if @checkins.empty? %>
      <div class="alert alert-danger" role="alert">Seja o primeiro a fazer esse checkin</div>
    <% else %>
      <ul class="list-group list-group-flush">
        <% @checkins.each do |checkin| %>
          <li class="list-group-item checkin check_<%= checkin.created_at.to_i%> text-light bg-dark">
            <%= checkin.bar.name %> <small><i>há <%= time_ago_in_words(checkin.created_at) %></i></small>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/checkins/edit.html.erb
<div class="row">
  <div class="card card--dark box-shadow mx-auto" style="max-width: 900px; important!">
    <div class="card-body md-8">
      <h3>Fazer Checkin</h3>
    </div>
    <div class="card-body data-list-container md-8">
      <ul class="list-group list-group-flush">
        <li class="list-group-item text-light bg-dark"><%= @full_description %></li>
        <li class="list-group-item text-light bg-dark">
          <%= form_for [@checkin.bar, @checkin] do |f| %>
            <div class="col-md-12"><%= f.label :description, 'Comentário' %></div>
            <div class="col-md-12"><%= f.text_area :description, size: '50x5' %></div>
            <div class="col-md-12"><%= f.submit 'Check-in', class: 'btn btn-primary' %></div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Bem vindo ao BeerSquare!!</h1>
<p>Aqui você encontra sua cerveja favorita nos bares de sua cidade</p>

app/views/layouts/_login.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <span class="navbar-text"><%= "Olá #{current_user.email}" %> | </span>
  </li>

  <li class="nav-item">
    <%= link_to 'Meu perfil', profile_path(current_user.id), class: 'nav-link' %>
  </li>

  <li class="nav-item">
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to('Login', new_user_session_path, class: 'nav-link') %>
  </li>

  <li class="nav-item">
    <%= link_to('Inscrever-se', new_user_registration_path, class: 'nav-link') %>
  </li>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
    <%= link_to 'BeerSquare', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'sr-only' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Bares', bars_path, class: (controller_name == 'bars')? 'nav-link active' : 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cervejas', search_beers_path, class: (controller_name == 'beers')? 'nav-link active' : 'nav-link' %>
        </li>
      </ul>

      <ul class="navbar-nav mr-auto justify-content-center">
          <%= render 'layouts/login' %>
        </li>
      </ul>
      <% if controller.controller_name == 'beers' %>
        <%= form_tag(search_school_beers_path, method: 'get', class: 'form-inline my-2 my-lg-0' ) do %>
          <%= label_tag(:q, "Escola Cervejeira", class: 'nav-link disabled') %>
          <%= select_tag(:q, options_for_select(SchoolBeer.all.map{|s| [s.name, s.id]}), {class: 'form-control mr-sm-2'}) %>
          <%= submit_tag('Filtrar', class: 'btn btn-outline-success my-2 my-sm-0') %>
        <% end %>
      <% end %>
      <%= form_tag(search_beers_path, method: 'get', class: 'form-inline my-2 my-lg-0' ) do %>
        <%= text_field_tag(:q, params[:q], {class: 'form-control mr-sm-2'}) %>
        <%= submit_tag('Buscar', class: 'btn btn-outline-success my-2 my-sm-0') %>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerSquare</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" style="margin-top: 65px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/edit.html.erb
<%= form_for @profile do |p| %>
  <div>
    <%= p.label :name, 'Nome' %>
    <%= p.text_field :name %>
  </div>
  <div>
    <%= p.label :birth_date, 'Data de nascimento' %>
    <%= p.text_field :birth_date, placeholder: 'dd/mm/aaaa' %>
  </div>
  <div>
    <%= p.submit 'Salvar' %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<h1>Meu perfil</h1>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<div class=''>
  <%= @profile.name %>
</div>

<div class=''>
  <%= @profile.birth_date %>
</div>

<%= link_to 'Editar', edit_profile_path(@profile) %>

app/views/school_beers/search.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title"><%= @school_beer.name %></h1>
        <ul class="list-group list-group-flush">
          <% @school_beer.beer_styles.each do |style| %>
            <li class="list-group-item">Estilo: <%= style.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_bar.html.erb
<div class="card card--dark md-5 box-shadow">
  <div class="card-img-top">
    <img src="http://www.veroverde.com.br/wp-content/uploads/2015/05/cropped-Panorama2.jpg" alt="">
  </div>
  <div class="card-body">
    <h3 class="card-title"><%= link_to bar.name, bar_path(bar) %></h3>
  </div>
  <div class="card-body data-list-container">
    <ul class="list-group list-group-flush">
      <li class="list-group-item text-light bg-dark"><%= fa_icon('map-marker') %> <%= bar.neighborhood %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('location-arrow') %> <%= bar.city %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('map') %> <%= bar.state %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('globe') %> <%= bar.zip_code %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('phone') %> <%= bar.phone %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('fort-awesome') %> <%= bar.trading_hour %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('money') %> <%= bar.payment %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('star') %> <%= bar.rank %></li>
      <li class="list-group-item text-light bg-dark"><%= fa_icon('spoon') %> <%= bar.services %></li>
    </ul>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>